# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pss_report_compiler_pb.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(310, 114)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_layout = QtWidgets.QVBoxLayout()
        self.pb_layout.setContentsMargins(-1, 8, -1, 8)
        self.pb_layout.setObjectName("pb_layout")
        self.label_layout = QtWidgets.QVBoxLayout()
        self.label_layout.setContentsMargins(-1, -1, -1, 8)
        self.label_layout.setObjectName("label_layout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.label_layout.addWidget(self.label)
        self.pb_layout.addLayout(self.label_layout)
        self.pb = QtWidgets.QProgressBar(Dialog)
        self.pb.setMaximum(0)
        self.pb.setProperty("value", 0)
        self.pb.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.pb.setObjectName("pb")
        self.pb_layout.addWidget(self.pb)
        self.verticalLayout.addLayout(self.pb_layout)
        self.btn_layout = QtWidgets.QHBoxLayout()
        self.btn_layout.setObjectName("btn_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btn_layout.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.btn_layout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.btn_layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Progress"))
        self.label.setText(_translate("Dialog", "Compiling Report..."))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
